global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s

scrape_configs:
  - job_name: "laravel_apps"
    scheme: https # tell Prometheus to use HTTPS
    metrics_path: /prometheus # your Laravel endpoint
    static_configs:
      - targets:
          - saasbrainstorm.com # host only; port 443 assumed
    tls_config:
      insecure_skip_verify: true # remove if site has a valid cert
